spring:
  graphql:
    graphiql:
      query: example/query.graphql
      default-editor-tools-visibility: VARIABLES
      variables:
        id: 1
      headers:
        x-test: test
      plugins: EXPLORER
      stylePath: /style.css
    voyager:
      style-path: /style.css