spring:
  graphql:
    graphiql:
      default-headers:
        x-test: test
      default-tabs:
        - query: |-
            query Query1($id: ID!) {
              artifactRepository(id: $id) {
                name
                url
              }
            }
          variables:
            id: 1
        - query: |-
            query Query2 {
              artifactRepositories {
                name
                url
              }
            }
      default-editor-tools-visibility: VARIABLES
      plugins: EXPLORER
      stylePath: /style.css
    voyager:
      allow-to-change-schema: true
      hide-voyager-logo: false
      headers:
        x-test: test
      style-path: /style.css