spring:
  graphql:
    graphiql:
      query: |-
        query($id: ID!) {
          artifactRepository(id: $id) {
            name
            url
          }
        }
      default-editor-tools-visibility: VARIABLES
      variables:
        id: 1
      headers:
        x-test: test
      plugins: EXPLORER
      stylePath: /style.css
    voyager:
      headers:
        x-test: test
      style-path: /style.css